// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "bdayBot/internal/user"
	models "bdayBot/internal/user/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddGroup mocks base method.
func (m *MockUserRepository) AddGroup(ctx context.Context, telegramID, groupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGroup", ctx, telegramID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGroup indicates an expected call of AddGroup.
func (mr *MockUserRepositoryMockRecorder) AddGroup(ctx, telegramID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroup", reflect.TypeOf((*MockUserRepository)(nil).AddGroup), ctx, telegramID, groupID)
}

// CreateOrUpdate mocks base method.
func (m *MockUserRepository) CreateOrUpdate(ctx context.Context, arg1 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockUserRepositoryMockRecorder) CreateOrUpdate(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockUserRepository)(nil).CreateOrUpdate), ctx, arg1)
}

// DeactivateUser mocks base method.
func (m *MockUserRepository) DeactivateUser(ctx context.Context, telegramID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, telegramID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockUserRepositoryMockRecorder) DeactivateUser(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockUserRepository)(nil).DeactivateUser), ctx, telegramID)
}

// FindByTelegramID mocks base method.
func (m *MockUserRepository) FindByTelegramID(ctx context.Context, telegramID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTelegramID indicates an expected call of FindByTelegramID.
func (mr *MockUserRepositoryMockRecorder) FindByTelegramID(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTelegramID", reflect.TypeOf((*MockUserRepository)(nil).FindByTelegramID), ctx, telegramID)
}

// GetBirthdaysInGroup mocks base method.
func (m *MockUserRepository) GetBirthdaysInGroup(ctx context.Context, groupID int64) ([]user.BirthdayInGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBirthdaysInGroup", ctx, groupID)
	ret0, _ := ret[0].([]user.BirthdayInGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBirthdaysInGroup indicates an expected call of GetBirthdaysInGroup.
func (mr *MockUserRepositoryMockRecorder) GetBirthdaysInGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBirthdaysInGroup", reflect.TypeOf((*MockUserRepository)(nil).GetBirthdaysInGroup), ctx, groupID)
}

// GetGroupsForUser mocks base method.
func (m *MockUserRepository) GetGroupsForUser(ctx context.Context, telegramID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupsForUser", ctx, telegramID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupsForUser indicates an expected call of GetGroupsForUser.
func (mr *MockUserRepositoryMockRecorder) GetGroupsForUser(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsForUser", reflect.TypeOf((*MockUserRepository)(nil).GetGroupsForUser), ctx, telegramID)
}

// GetTodaysBirthdays mocks base method.
func (m *MockUserRepository) GetTodaysBirthdays(ctx context.Context, day, month int) ([]*user.BirthdayDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodaysBirthdays", ctx, day, month)
	ret0, _ := ret[0].([]*user.BirthdayDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodaysBirthdays indicates an expected call of GetTodaysBirthdays.
func (mr *MockUserRepositoryMockRecorder) GetTodaysBirthdays(ctx, day, month any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodaysBirthdays", reflect.TypeOf((*MockUserRepository)(nil).GetTodaysBirthdays), ctx, day, month)
}

// ReactivateUser mocks base method.
func (m *MockUserRepository) ReactivateUser(ctx context.Context, telegramID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReactivateUser", ctx, telegramID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReactivateUser indicates an expected call of ReactivateUser.
func (mr *MockUserRepositoryMockRecorder) ReactivateUser(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReactivateUser", reflect.TypeOf((*MockUserRepository)(nil).ReactivateUser), ctx, telegramID)
}

// RemoveGroup mocks base method.
func (m *MockUserRepository) RemoveGroup(ctx context.Context, telegramID, groupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGroup", ctx, telegramID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveGroup indicates an expected call of RemoveGroup.
func (mr *MockUserRepositoryMockRecorder) RemoveGroup(ctx, telegramID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroup", reflect.TypeOf((*MockUserRepository)(nil).RemoveGroup), ctx, telegramID, groupID)
}
